src/Entity/Proprety.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropretyRepository")
 */
class Proprety
{
    const HEAT=[
        0=>'Eléctrique',
        1=>'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $badrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean",options={"default": false})
     */
    private $sold =false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;
    public function __construct()
    {
        $this->created_at=new \DateTime(); //pour préremplie la date quoi qi'il arrive
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug():string {
        return (new Slugify())->slugify($this->title);

    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBadrooms(): ?int
    {
        return $this->badrooms;
    }

    public function setBadrooms(int $badrooms): self
    {
        $this->badrooms = $badrooms;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormatPrice(): string {
        return number_format($this->price,0, '', ' ');
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }


    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string{
       return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/BiensController.php
<?php

namespace App\Controller;

use App\Entity\Proprety;
use App\Repository\PropretyRepository;
use Doctrine\ORM\EntityManagerInterface;  //doctrine.orm.default_entity_manager
//use Doctrine\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;


class BiensController extends AbstractController
{

     // cette methode pour dire que j'aimerai bien recuperer le repository
     // et si on a plein de methode qui ont besoin de la repository il vaut mieux
     // d'utiliser le connstruct sinon on peut l'injecter dans la methode qui l'a besoin
     //
    /**
     * @var PropretyRepository
     */

    private $repository;

    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(PropretyRepository $repository ,EntityManagerInterface $em)
    {
        $this->repository=$repository;
        $this->em=$em;

    }

    /**
     * @Route("/biens", name="biens.index")
     * @return Response
     */
    public function index(): Response
    {

        //POUR METTRE A JOUR MON ENTITE
        /*
          $proprety=$this->repository->findAllVisible();
          $proprety[0]->setSold(true);
           $this->em->flush();
        */
        return $this->render('biens/index.html.twig', ['current_menu' => 'bien']);
    }
    /**
     * @Route("/biens/{slug}-{id}", name="biens.show", requirements={"slug":"[a-z0-9\-]*"})
     * @param $slug
     * @param $id
     * @return Response
     */
    public function show( Proprety $proprety,string $slug):Response{

        if($proprety->getSlug()!== $slug){
           return $this->redirectToRoute('biens.show',[
               'id'   =>$proprety->getId(),
               'slug' =>$proprety->getSlug()
            ],301);
        }
        return $this->render('biens/show.html.twig',[
                                    'proprety'=>$proprety,
                                    'current_menu'=>'bien'

        ]);
    }
}



       /* $em=$this->getDoctrine()->getManager();
        $proprety=new Proprety(); //pour creer unenouvelle enregistrement
        $proprety->setTitle("mon premier bien")
            ->setPrice(200000)
            ->setRooms(4)
            ->setBadrooms(3)
            ->setDescription("une petite description ")
            ->setSurface(60)
            ->setFloor(4)
            ->setHeat(1)
            ->setCity('Montpiller')
            ->setAdresse('15 istres')
            ->setPostalCode(13800);


        $em->persist($proprety); //j'aimerai bien de persiste (enregistre) mon entite
        $em->flush();  //ça va me d'envoyer et de  porter tous changement qui a ete faite au niveau de l'enitite manager dans la BD*/

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\PropretyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     * @param PropretyRepository $repository
     * @return Response
     */

    public function index(PropretyRepository $repository): Response
    {
        $propreties=$repository->findLatest();
        return $this->render('home/index.html.twig',
                             ['propreties'=>$propreties]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        {% block stylesheets %}{% endblock %}

    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{{ path('home') }}">Mon Agence</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if current_menu is defined and current_menu=='bien'%}active{% endif %}">
                    <a class="nav-link" href="{{ path('biens.index') }}">Acheter</a>
                </li>



            </ul>

        </div>
    </nav>

        {% block body %}{% endblock %}

        {% block javascripts %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


    </body>
</html>

templates/biens/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BiensController!{% endblock %}

{% block body %}


<div >
    <h1>Nos Biens</h1>


</div>
{% endblock %}

templates/biens/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}

{% block body %}
   <div class="jumbotron">
      <div class="container">
      <div class="row">
         <div class="col-md-8">

         </div>
         <div class="col-md-4">
            <h1>{{ proprety.title }}</h1>
            <h2>{{ proprety.rooms }} Pièce {{proprety.surface }} m2 </h2>
            <div class="text-primary">{{ proprety.formatPrice }}</div>
            <a href="" calss="btn btn-primary"> Contacter l'agence</a>
         </div>
      </div>
   </div>
   </div>
<div class="container mt-4" >

   <p>
      {{ proprety.description |nl2br}}
   </p>

   <div class="row">
      <div class="col-md-8">
         <h2>Caractéristique</h2>
            <table class="table table-striped">
               <tr>
                  <td>Surface habitable</td>
                  <td>{{ proprety.surface }}</td>
               </tr>
               <tr>
                  <td>Pièces</td>
                  <td>{{ proprety.rooms }}</td>
               </tr>
               <tr>
                  <td>Chambre</td>
                  <td>{{ proprety.badrooms }}</td>
               </tr>
               <tr>
                  <td>Etage</td>
                  <td>{{ proprety.floor }}</td>
               </tr>
               <tr>
                  <td>Chauffage</td>
                  <td>{{ proprety.heatType }}</td>
               </tr>


            </table>
      </div>
      <div class="col-md-4">
         <h2>Spécificité</h2>
      </div>
   </div>
</div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
<div class="jumbotron text-center">
    <h1>Agence Immobilier</h1>
    <p>composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n'a pas fait que survivre cinq siècles, mais s'est aussi adapté à la bureautique informatique, sans que son contenu n'en</p>
</div>


<div class="container">
   <h2>Les derniers biens</h2>
   <div class="row flex">
      {% for proprety in propreties %}
          <div class="col-4">
              <div class="card">
                  <div class="card-body">
                      <h5 class="card-title">
                          <a href="{{ path('biens.show', {id: proprety.id ,slug: proprety.slug}) }}">{{ proprety.title }}</a>
                      </h5>
                      <p class="card-text">{{ proprety.city }} ({{ proprety.postalCode }})</p>
                      <div class="text-primary" style="font-weight: bold; font-size: 2rem  ">{{ proprety.getFormatPrice() }}€</div>
                  </div>
              </div>
          </div>
      {% endfor %}
   </div>

</div>

{% endblock %}